#!/usr/bin/env ruby
# Code modified from: https://gist.github.com/hanloong/9849098
require 'English'

ADDED_OR_MODIFIED = %r{A|AM|M|^M}

changed_files = `git status --porcelain`.split(%r{\n})
changed_files = changed_files.select do |file_name_with_status|
  file_name_with_status =~ ADDED_OR_MODIFIED
end
changed_files = changed_files.map do |file_name_with_status|
  file_name_with_status.split(' ')[1]
end
changed_files = changed_files.select { |file_name|
  File.extname(file_name) == '.rb'
}.join(' ')

system("bundle exec rubocop -a #{changed_files}") unless changed_files.empty?

if $CHILD_STATUS.to_s[-1].to_i.zero? && !changed_files.empty?
  system("git add #{changed_files}")
end
exit $CHILD_STATUS.to_s[-1].to_i
