#!/usr/bin/env ruby
# frozen_string_literal: true

# Code modified from: https://gist.github.com/hanloong/9849098
require 'English'

changed_files = `git diff --name-only --cached --diff-filter=ACM`.split(/\n/)
changed_files = changed_files.select do |file_name|
  File.extname(file_name) == '.rb'
end.join(' ')

system("bundle exec rubocop -a #{changed_files}") unless changed_files.empty?

system("git add #{changed_files}") if $CHILD_STATUS.to_s[-1].to_i.zero? && !changed_files.empty?

exit $CHILD_STATUS.to_s[-1].to_i
