---
inherit_from: .rubocop_todo.yml

require: rubocop-rspec
AllCops:
  TargetRubyVersion: '2.5'
  Include:
  - "**/*.rb"
  Exclude:
  - bin/*
  - ".vendor/**/*"
  - Gemfile
  - Rakefile
  - pkg/**/*
  - spec/fixtures/**/*
  - vendor/**/*

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - is

Lint/NestedMethodDefinition:
  Exclude:
    - 'lib/puppet/resource_api.rb'
